from os.path import abspath, join, dirname


class Content:
    def __init__(self):
        
        self.about_us_content: dict= {
            "EN": {
                "whoAreWe": "was founded in 2019. An entity that is responsible for providing traders with the best experience in Forex, and deliver one message: «TRADE ON THE RIGHT WAY».",
                "vision": "- Install the right trading culture in the Middle East as a type of profitable investment that the whole world needs in recent times.\n\n-Reach the best international standards in Forex World.\n\n-Learn how to make money by trading. \n\n- Present comprehensive services in the world of financial markets through various methods that help traders achieve the greatest profit intelligently.\n\n- Spread the West's approach to trading and considering it an investment that must be learned properly to reap the largest profits.",
                "mission": "- Focus on providing quality financial services\n\n- Provide reliable financial advice.\n\n- Create safe and reliable investments.\n\n- Adhere to ethical practices .\n\n- Help clients secure their financial future.\n\n- Provide excellent customer service.\n\n- Teach the public to trade the right way.\n\n- Warning against companies that use the term “trading” in order to delude the public into obtaining large profits without learning.\n\n- Availability of free educational value to teach the basics of trading.\n\n- View the latest trading strategies and share them with traders.",
                "education": "Education",
                "educationContent": "- Online Courses.\n\n- Offline Courses.\n\n- Free educaional content for beginners and advcanced audience.\n\n- Free Webinars.\n\n- Outdoor Events.",
                "informing": "Informing",
                "informingContent": "- Daily News on Our Website and platforms.\n\n- Articles on website.\n\n- Anylsing.\n\n- Weekly Economic Agenda.",
                "trading": "Trading",
                "tradingContent": "- Consulting.\n\n- Recommendatins.\n\n- Open Accounts.\n\n- Competations.",
            },
            "AR": {
                "whoAreWe": "تأسست عام 2019. كيان مسؤول لتزويد المتداولين بأفضل تجربة في الفوركس، وإيصال رسالة واحدة: التداول على الطريق  الصحيح",
                "vision": "-تثبيت  ثقافة التداول الصحيحة في الشرق الأوسط كنوع من الاستثمار المربح الذي يحتاجه العالم كله في الآونة الأخيرة.\n\n-الوصول إلى أفضل المعايير العالمية في عالم الفوركس.\n\n-تعلم كيفية كسب المال عن طريق التداول.\n\n- تقديم خدمات شاملة في عالم المال\n\n- الأسواق من خلال وسائل مختلفة تساعد المتداولين تحقيق أكبر قدر من الربح بذكاء.\n\n- نشر منهج الغرب في التجارة والنظر فيه استثمار يجب تعلمه بشكل صحيح لجني ثماره أكبر الأرباح",
                "mission": "- التركيز على تقديم خدمات مالية عالية الجودة\n\n- تقديم المشورة المالية الموثوقة.\n\n- خلق استثمارات آمنة وموثوقة.\n\n- الالتزام بالممارسات الأخلاقية.\n\n- مساعدة العملاء على تأمين مستقبلهم المالي.\n\n- تقديم خدمة عملاء ممتازة.\n\n- تعليم الجمهور التجارة بالطريقة الصحيحة.\n\n- التحذير من الشركات التي تستخدم مصطلح \"التداول\" بهدف التضليل\n\nالجمهور للحصول على أرباح كبيرة دون التعلم.\n\n- توافر قيمة تعليمية مجانية لتعليم أساسيات التداول.\n\n- عرض أحدث استراتيجيات التداول ومشاركتها مع المتداولين",
                "education": "التعليم",
                "educationContent": "-  دروس مباشرة على الإنترنت.\n\n- دورات أوفلاين.\n\n- محتوى تعليمي مجاني لـ المبتدئين والمتقدمين\n\n- ندوات عبر الإنترنت مجانية.\n\n- الفعاليات الخارجية",
                "informing": "أخبار",
                "informingContent": "- الأخبار اليومية على موقعنا \والمنصات.\n\n- مقالات على الموقع.\n\n- تحليلات.\n\n- الأجندة الاقتصادية الأسبوعية.",
                "trading": "تداول",
                "tradingContent": "-الاستشارة-\n\nالتوصيات.\n\n- حسابات مفتوحة.\n\n- المسابقات.",

            }
        }
        self.global_: dict = {
            "EN": {
                "platformTitle": "Sky Elevators",
                "homeServicesSectionTitle": "Ascend to New Heights",
                "homeSerivceInstallationsTitle":"Installations",
                "homeSerivceInstallationsBio":"Seamless Installations for Elevating Your Spaces Safely",
                "homeSerivceModernizationTitle":"Modernization",
                "homeSerivceModernizationBio":"Smart Solutions for Elevator Efficiency and Profit Optimization",
                "homeSerivceMaintenanceTitle":"Maintenance",
                "homeSerivceMaintenanceBio":"Elevate Your Uptime with Expert Elevator Care Services",
                "homeSerivceSparePartsTitle":"Spare Parts",
                "homeSerivceSparePartsBio":"Quality Spare Parts to Keep Your Elevators Ascending Smoothly",
                "homeServicesSectionBio": "Ride the Future: Elevating Experiences with Cutting-Edge Elevator Solutions",
                "homeBlogSectionTitle": "Our Blog",
                "homeTestmonialsSectionTitle": "Rave Reviews",
                "homeValuesSectionTitle": "Core Elevator Values",
                "homeValuesSectionBio": "Elevating with Integrity, Innovation, and Excellence – Our Pillars of Success",
                "homeValuesSectionValesOne": "Pioneering advancements in elevator technology for enhanced efficiency and reliability.",
                "homeValuesSectionValesTwo": "Ensuring consistent, safe, and dependable elevator solutions for our clients.",
                "homeValuesSectionValesThree": "Committed to understanding and meeting the unique needs of each customer.",
                "homeTestmonialsSectionBio": "Discover what others say about our elevating services and customer satisfaction",
                "homeProjectManagementSectionTitle": "<span>Amidst the quest for excellence, we manage our safety-compliant projects to deliver   the best quality in a timely manner.</span><br>Project MGT",
                "homeProjectManagementSectionBio": "With every project, we embark on a journey of coordination, synchronizing the site’s conditions and required activities for the benefit of the project. This process spans from the site preparatory works plan, through the safety and quality plan, to the execution plan, while customer meetings and periodic reports keep the process flowing perfectly and smoothly.",
                "homeShopSectionTitle": "Premium Elevator Parts",
                "homeShopSectionBio": "Elevate your experience with top-quality spare parts for unmatched performance.",
                "shortDescription": "was founded in 2019. An entity that is responsible for providing traders with the best experience in Forex, and deliver one message: «TRADE ON THE RIGHT WAY».",
                "blogWelcomingMsg": "Welcome to <span class='highlighted'>Sky Elevators</span> Blog<br><span class='subtitle'>Where you can find <span class='highlighted'>craft narratives</span> that ignite <span class='highlighted'>inspiration</span>, <span class='highlighted'>knowladge</span>, and <span class='highlighted'>entertainment<span>!</span>",
                "lightToFindUs": "Trade on the right way!",
                "copyrightMsg": "All Copyrights reserved @ Sky Elevators, 2024",
                "contactUsTitle": "Light to <span class='highlighted'>Find Us</span>",
                "contactUsSubtitle": "We will be happy to hear from you!",
                "aboutEntrySectionTitle": "Skyward Journeys",
                "aboutEntrySectionSubtitle": "Elevator Solutions Reaching Every Level",
                "ourStoryTitle": "Our Story",
                "ourStory": "Sky elevators is a leading provider of elevator solutions, aiming to make people flow safe, reliable and convenient.\n\nWe provide superior installation, maintenance and modernization services for all types of elevators in all types of buildings, guaranteeing the highest safety and quality standards.",
                "competitiveEdgeTitle": "Competitive Edge",
                "competitiveEdge": "Our expertise in innovative engineering solutions, which empower us to customize our services to each client’s unique needs.",
                "aboutValuesSectionTitle": "Elevating Trust",
                "aboutValuesSectionSubtitle": "Commitment to Quality & Safety",
                "aboutValuesSectionValuesOneTitle": "Integrity",
                "aboutValuesSectionValuesOneDesc": "Honesty and transparency guide every interaction. Trust us to deliver with ethical practices and clear communication. ",
                "aboutValuesSectionValuesTwoTitle": "Reliability",
                "aboutValuesSectionValuesTwoDesc": "Your project's success is our promise. We ensure timely completion and stay within budget, exceeding expectations.",
                "aboutValuesSectionValuesThreeTitle": "Innovation",
                "aboutValuesSectionValuesThreeDesc": "We embrace cutting-edge technologies to provide the most advanced elevator solutions, pushing boundaries for a smoother ride.",
                "aboutValuesSectionValuesFourTitle": "Safety",
                "aboutValuesSectionValuesFourDesc": "Your well-being is paramount. We adhere to the strictest safety regulations and implement rigorous protocols for every installation.",
                "aboutValuesSectionValuesFiveTitle": "Quality",
                "aboutValuesSectionValuesFiveDesc": "Unwavering commitment to excellence in every aspect. We use premium materials and meticulous craftsmanship for elevators built to last.",
                "aboutValuesSectionValuesSixTitle": "Pioneering",
                "aboutValuesSectionValuesSixDesc": "We lead the industry by constantly seeking advancements. Expect groundbreaking solutions and a dedication to shaping the future of elevators.",
                "meetSkyFounderTile": "Meet Sky Founder & General Manager",
                "meetSkyFounderDescription": "Eng. Mohamed Elsherbiny who has over 25 years of experience in the industry in multinational companies such as Otis and Kone As a director of various areas such as major projects, sales operation, maintenance, and safety",
                "meetSkyFounderDegreesTitle": "Degrees and certifications:",
                "meetSkyFounderDegrees": ["Master’s Degree in business administrations - AAST", "NEBOSH", "Major projects academy- London/Paris", "OSHA", "EHS & quality auditor - middle east and Europe."],
                "aboutQualityCodesTitle": "Unlocking Safety & Performance",
                "aboutQualityCodesSubtitle": "Certifications That Speak Volumes",
                "aboutQualityCodesSnippetOne": "The European code of elevators EN81-20/50",
                "aboutQualityCodesSnippetTwo": "The Egyptian code of elevators 303/2007",
                "aboutQualityCodesSnippetThree": "The worldwide job site safety standard WWJSSS",
                "aboutOurVisionTitle": "New Heights Await",
                "aboutOurVision": 'At Sky Elevators, we envision a future where architectural marvels seamlessly connect with <span class="highlighted">cutting-edge elevator technology</span>, empowering builders and dreamers to reach previously <span class="highlighted">unimagined heights</span>.<br><br>Driven by our <span class="highlighted">unwavering commitment to innovation and expertise</span>, we strive to be the trusted partner for engineers, architects, and project managers, providing <span class="highlighted">customizable, high-quality elevator solutions</span> that elevate more than just people - they elevate possibilities.<br><br>We believe in <span class="highlighted">affordable accessibility</span>, ensuring <span class="highlighted">budget-friendly combined components</span> that never compromise on <span class="highlighted">performance or safety</span>. Our vision isn\'t just about rising higher, it\'s about removing barriers and opening doors to <span class="highlighted">limitless potential</span>.<br><br>Fueled by a <span class="highlighted">competitive edge in innovative engineering solutions</span>, we <span class="highlighted">customize every project to meet unique needs</span>, turning blueprints into soaring realities. By partnering with us, you gain more than just elevators; you gain a team dedicated to your success, committed to pushing boundaries and reaching <span class="highlighted">new heights of excellence, together</span>.\nThis is the Sky Elevators vision. <span class="highlighted">Ascend with us.</span>',
                "installationsEntryTitle": "Elevate Your Space",
                "installationsEntrySubtitle": "Seamlessly integrating technology, sourcing, load capacity, speed, and height for your perfect fit",
                "installationsGearedSectionTitle":"Power & Precision",
                "installationsGearedSectionSubtitle":"Reliable performance, built for lasting durability",
                "installationsGearedSectionStopsLabel":"Up to 12 stops",
                "installationsGearedSectionPeopleLabel":"4 to 8 persons",
                "installationsGearedSectionSpeedLabel":"Up to 1.6 m/sec",
                "installationsGearlessSectionTitle":"Silent Glide, Future Tech",
                "installationsGearlessSectionSubtitle":"Smooth, quiet operation meets energy efficiency",
                "installationsGearlessSectionStopsLabel":"Up to 12 stops",
                "installationsGearlessSectionPeopleLabel":"4 to 8 persons",
                "installationsGearlessSectionSpeedLabel":"Up to 1.6 m/sec",
                "installationsHomeLiftsSectionTitle":"Stylish Home Ascent",
                "installationsHomeLiftsSectionSubtitle":"Seamless accessibility, designed for effortless living",
                "installationsHomeLiftsSectionStopsLabel":"Up to 5 stops",
                "installationsHomeLiftsSectionPeopleLabel":"2 to 4 persons",
                "installationsHomeLiftsSectionSpeedLabel":"1 m/sec0.63 m/sec",
                "installationsHydrolicElevatorsSectionTitle":"Strengthful & Adaptable",
                "installationsHydrolicElevatorsSectionSubtitle":"Powerful lifting, versatile for any space and load",
                "installationsInqueryTitle":"Few Preparatory Works!",
                "installationsInquerySubtitle":"Skip the hassle! Get your installation finished with minimal disruption to your space. We'll take care of everything with as little preparatory work as possible.",
                "installationsWeServeResidentialBuildings": "Residential Buildings",
                "installationsWeServeShoppingMalls": "Shopping Malls",
                "installationsWeServeHotels":"Hotels & More",
                "installationsWeServeOfficeBuildings":"Office Buildings",
                "installationsWeServe":"Partnering with Leaders of...",
                "installationsWeServeSubtitle":"Driving success alongside industry's best.",
                "installationsWeServeResidentialBuildingsDescription":"Sky Elevators offers quiet, stylish residential elevators that seamlessly blend with your home.  Choose from modern glass or classic wood designs to elevate your comfort, convenience, and property value.",
                "installationsWeServeShoppingMallsDescription":"Get your mall buzzing with Sky Elevators' high-traffic commercial solutions.  Our intelligent dispatch systems minimize wait times and customizable finishes create a seamless shopping experience.",
                "installationsWeServeHotelsDescription":"Sky Elevators streamlines your office with fast, reliable elevators.  Advanced technology minimizes wait times and 24/7 maintenance keeps your tenants productive.",
                "installationsWeServeOfficeBuildingsDescription":"Make a lasting impression with Sky Elevators' luxurious hotel elevators.  Our quiet, spacious designs and 24/7 maintenance ensure guest comfort and safety.  Focus on creating memorable experiences, not elevator worries.",
                "installationsAllTypeOfInstallationsTitle": "All-Type Elevator Installation",
                "installationsAllTypeOfInstallationsSubtitle": "We install all types of elevators in Egypt!",
                "installationsAllTypeOfInstallationsTechnologies": "Technologies",
                "installationsAllTypeOfInstallationsTechnologiesBio": "Cutting-edge elevator solutions.",
                "installationsAllTypeOfInstallationsSourcing": "Sourcing",
                "installationsAllTypeOfInstallationsSourcingBio": "Expert sourcing for top elevator brands.",
                "installationsAllTypeOfInstallationsLoads": "Loads",
                "installationsAllTypeOfInstallationsLoadsBio": "Elevators designed for all weight capacities.",
                "installationsAllTypeOfInstallationsSpeeds": "Speeds ",
                "installationsAllTypeOfInstallationsSpeedsBio": "Optimizing elevator speed for your needs. ",
                "installationsAllTypeOfInstallationsHeights": "Heights",
                "installationsAllTypeOfInstallationsHeightsBio": "Serving any building height with expertise.",
                "modernizationEntryTitle": "Revamp, Upgrade, Elevate",
                "modernizationEntrySubtitle": "Transforming Outdated Elevators into High-Performance, Efficient, and Safe Systems",
                "modernizationMachinesTitle": "Machines",
                "modernizationMachinesSubtitle": "Outdated single-speed or two-speed elevator machines might be nearing retirement. Modernize your building with a sleek, multi-speed replacement. Enjoy smoother, quieter rides, reduced energy consumption, and improved efficiency. Invest in the future of your building's comfort and value.",
                "modernizationDoorsTitle": "Doors",
                "modernizationDoorsSubtitle": "Upgrading your entryway? Decide between automatic doors' effortless access and modern look, or manual doors' budget-friendly charm and design flexibility. Consider traffic flow, budget, aesthetics, and energy efficiency for the perfect fit!",
                "modernizationControllersTitle": "Controllers & inverters",
                "modernizationControllersSubtitle": "Is your elevator feeling sluggish or outdated? Consider a revitalizing replacement of its controllers and drives. This upgrade unlocks smoother rides, improved efficiency, and potentially lower energy costs. Plus, modern controllers often offer enhanced safety features and remote monitoring. Invest in a revamped elevator experience that benefits both riders and building management.",
                "modernizationDecorationsTitle": "Decorations & fixtures",
                "modernizationDecorationsSubtitle": "Tired of boring elevator rides? Liven up your building with creative decor! Mirrors and textured walls add visual interest, while nature murals relax and digital displays entertain. Choose warm lights for coziness, cool lights for modernity. Accessibility matters: clear signs and easy-to-reach buttons are key! Uplift your elevator experience!",
                "maintenanceEntryTitle": "Elevated Care",
                "maintenanceEntrySubtitle": "Maximize uptime, minimize stress",
                "maintenanceSerivcesSectionTitle": "Happy Elevators, Happy Passengers",
                "maintenanceSerivcesSectionSubtitle": "Ensuring smooth rides and positive experiences",
                "maintenanceServicesCardOneTitle": "Extend Equipment Life",
                "maintenanceServicesCardOneBio": "Our professional systems and highly trained mechanics ensure comprehensive and efficient elevator maintenance. This proactive approach minimizes wear and tear, extending the lifespan of your valuable equipment and saving you money in the long run.",
                "maintenanceServicesCardTwoTitle": "Unmatched Expertise",
                "maintenanceServicesCardTwoBio": "Our team of qualified mechanics undergoes rigorous training to stay up-to-date on the latest industry standards and technologies. This ensures your elevator receives the specialized care it deserves, guaranteeing smooth operation and passenger safety.",
                "maintenanceServicesCardThreeTitle": "Customer Satisfaction Guaranteed",
                "maintenanceServicesCardThreeBio": "Our primary objective is your complete satisfaction. We achieve this by providing exceptional service, clear communication, and a dedication to keeping your elevator running flawlessly. With our commitment to excellence, you can rest assured that your passengers will always have a positive and reliable experience.",
                "maintenancePreventingMaintenanceTitle": "<span>Prevent Downtime, <br></span>Extend Lifespan!",
                "maintenancePreventingMaintenanceParagraph": "Why wait for your elevator to break down when you can prevent problems before they start? Our professional preventive and predictive maintenance programs are designed to identify and address potential issues before they escalate into major repairs or even complete elevator replacement. This proactive approach not only saves you money in the long run but also ensures smooth and reliable operation, keeping your passengers happy and your building running efficiently.",
                "maintenanceSafetyTitle": "<span>Uncompromising Safety and Quality<br></span>Your Peace of Mind!",
                "maintenanceSafetyParagraph": "Maintaining passenger safety and the optimal performance of your elevator are our top priorities. We conduct thorough and periodic safety and quality inspections, To ensure customer satisfaction, our maintenance department operates around the clock, ready to address inquiries and calls promptly. We meticulously analyze callbacks to develop proactive strategies, preventing recurring breakdowns and exceeding expectations at every interaction.",
                "sparePartsEntryTitle": "Elevator Parts",
                "sparePartsEntrySubtitle": "Keep Your Lifts Running Smoothly",
                "search": "Search",
                "trendingNow": "Trending Now",
                "dontHaveAccount": "Don't have an account? Join us now!",
                "alreadyHaveAccount": "Have an account? Login now!",
                "name": "Name",
                "phoneNumber": "Phone Number",
                "email": "Email",
                "password": "Password",
                "homeEntryMsg": "Ascend to New Heights!",
                "mostRecent": "Most Recent",
                "allArticles": "All Articles",
                "random": "Random",
                "all": "All",
                "ourLatestArticles": "Our Latest Articles",
                "ourArticles": "Our Articles",
                "featured": "Featured",
                "trending": "Trending",
                "ourBestWriters": "Our best <br><span>Writers</span>",
                "incaseYouMissed": "In Case You Missed!",
                "incaseYouMissedMsg": "In case you missed these articles, Check them out now!",
                "randomArticles": "Random Articles!",
                "randomArticlesMsg": "Based on your pervious choises, We've picked these articles for you!",
                "wannaJoinUs": "Curious about<br><span> Joining Us</span>",
                "applications": "Applications",
                "le": "L.E.",
                "classification": "Classification",
                "classifications": "Classifications",
                "category": "Category",
                "categories": "Categories",
                "writer": "Writer",
                "writers": "Writers",
                "articles": "Articles",
                "writtenBy": "Written By",
                "unavailable": "Unavailable",
                "listenMsg": "Listen to the article!",
                "unavailableMsg": "The article audio not available!",
                "shareMsg": "Share this article!",
                "rateMsg": "Rate this article!",
                "commentMsg": "Leave a comment!",
                "whatsYouWantToRead": "You want to read what?",
                "whatsYouWantToReadMsg": "Choose what do you want to read!",
                "filter": "Filter",
                "filterMsg": "Get the exact articles you're searching for!",
                "articleTitle": "Article Title",
                "discoverCategories": "Discover our <span class=\"underline\">Categories</span>",
                "discoverCategoriesMsg": "We've classified our articles to make it easy for you to find what you are searching for!",
                "featuredCategories": "Featured Categories",
                "featuredCategoriesMsg": "We've chosen these categories for you!",
                "allCategories": "All Categories",
                "allCategoriesMsg": "Check out all categories we have!",
                "latestArticles": "Latest Articles",
                "latestArticlesMsg": "Discover the latest articles now!",
                "careers": "Careers",
                "resetYourPassword": "Reset your password",
                "profilePicture": "Profile Picture",
                "coverPicture": "Cover Picture",
                "allCareers": "All Careers",
                "weSearchingForYou": "We're searching for you like you do!",
                "riskwarning": "Risk Warning",
                "riskwarningMsg": "Trading using leverage in the financial markets involves very high risks that are not suitable for all types of investors. You must understand the amount of risk that your money may be exposed to. All opinions, analyses, recommendations and content presented on the site are for general information and should not be taken as a tool for making any investment decisions, whether to buy or sell.",
                "agenda": "Economic Agenda",
                "agendaMsg": "Follow up the news and times that affect marketplaces!",
                "welcomeBack": "Welcome Back",
                "aboutMsg": "Curious about know more about us?",
                "coursesMsg": "Start your journey to \"Trade on the Right way\"!",
                "price": "Price", 
                "sessions": "Sessions",
                "courseContent": "Course Content",
                "students": "Students",
                "next_session": "Next Session",
                "support": "Support",
                "complaint": "Complaint",
                "feedback": "Feedback",
            },
            "AR": {
                "platformTitle": "سكاي",
                "shortDescription": "تأسست عام 2019. كيان مسؤول لتزويد المتداولين بأفضل تجربة في الفوركس، وإيصال رسالة واحدة: التداول على الطريق  الصحيح",
                "lightToFindUs": "تداول على الطريقة الصحيحة!",
                "copyrightMsg": "All Copyrights reserved @ Sky Elevators, 2023",
                "search": "بحث",
                "trendingNow": "شائع الآن",
                "dontHaveAccount": "ليس لديك حساب؟ انضم إلينا الآن!",
                "alreadyHaveAccount": "هل لديك حساب؟ سجل الدخول الآن!",
                "name": "الاسم",
                "phoneNumber": "رقم الهاتف",
                "email": "البريد إلكتروني",
                "password": "كلمة المرور",
                "homeEntryMsg": "أفضل ما في الأسبوع",
                "mostRecent": "الأحدث",
                "allArticles": "جميع المقالات",
                "random": "عشوائي",
                "all": "الكل",
                "ourLatestArticles": "أحدث المقالات",
                "ourArticles": "المقالات",
                "featured": "المُختار",
                "trending": "الشائع",
                "ourBestWriters": "أفضل <br><span>الكُتّاب</span> لدينا",
                "incaseYouMissed": "مقالات ذات صلة",
                "incaseYouMissedMsg": "في حال فاتتك هذه المقالات ، تحقق منها الآن!",
                "randomArticles": "مقالات آخرى!",
                "randomArticlesMsg": "بناءً على اختياراتك السابقة ، اخترنا لك هذه المقالات!!",
                "wannaJoinUs": "مهتم بأن<br><span>تنضم إلينا</span>",
                "applications": "المتقدمين للوظيفة",
                "le": "L.E.",
                "classification": "التصنيف",
                "classifications": "التصنيفات",
                "category": "الفئة",
                "categories": "الفئات",
                "writer": "الكاتب",
                "writers": "الكُتًاب",
                "articles": "المقالات",
                "writtenBy": "كٌتبت بواسطة",
                "unavailable": "غير متوفر",
                "listenMsg": "إستمع إلى المقال!",
                "unavailableMsg": "النسخة الصوتية من المقال غير متوفرة!",
                "shareMsg": "أنشر هذا المقال!",
                "rateMsg": "قيم هذا المقال!",
                "commentMsg": "اترك تعليقاً!",
                "whatsYouWantToRead": "ماذا تريد أن تقرأ؟",
                "whatsYouWantToReadMsg": "اختر ما تريد قراءته!",
                "filter": "بحث",
                "filterMsg": "احصل على المقالات التي تبحث عنها!",
                "articleTitle": "عنوان المقال",
                "discoverCategories": "تفقد <span class=\"underline\">الفئات</span> التي نتناولها",
                "discoverCategoriesMsg": "لقد قمنا بتصنيف مقالاتنا لتسهيل العثور على ما تبحث عنه!",
                "featuredCategories": "الفئات المختارة",
                "featuredCategoriesMsg": "الفئات التي قمنا بإختيارها لك!",
                "allCategories": "الفئات",
                "allCategoriesMsg": "تفقد جميع الفئات التي نتناولها",
                "latestArticles": "أحدث المقالات",
                "latestArticlesMsg": "تفقد أخر المقالات المنشورة!",
                "careers": "الوظائف",
                "resetYourPassword": "إسترجع كلمة مرور حسابك",
                "profilePicture": "الصورة الشخصية",
                "coverPicture": "صورة الغلاف",
                "allCareers": "جميع الوظائف",
                "weSearchingForYou": "نحن نبحث عنك كما تفعل!",
                "riskwarning": "تحذير المخاطرة",
                "riskwarningMsg": "المتاجرة باستخدام الروافع المالية في أسواق المال ينطوي عليها مخاطر عالية جدًا لا تتناسب مع جميع أنواع المستثمرين، يجب عليك أن تستوعب حجم المخاطرة التي قد تتعرض لها أموالك. جميع ما يطرح في الموقع من آراء وتحليلات وتوصيات ومحتويات هو من باب المعلومات العامة ولا يجب أن يتخذ كأداة لاتخاذ أي قرارات استثمارية بالبيع أو الشراء. ",
                "agenda": "الأجندة الإقتصادية",
                "agendaMsg": "تابع الأخبار والمواقيت التي ترثؤ على الأسواق المالية!!",
                "welcomeBack": "أهلاً بعودتك",
                "aboutMsg": "مهتم أن تعرف المزيد عن من نكون؟",
                "coursesMsg": "أبدأ رحلتك في التداول بالطريقة الصحيحة",
                "price": "السعر", 
                "sessions": "المحاضرات",
                "courseContent": "محتوى الدورة",
                "students": "عدد الطلاب",
                "next_session": "المحاضرة القادمة"
            }
        }

        self.tabs: dict = {
            "EN": {
                "home": "Home",
                "maintenance": "Maintenance",
                "spareParts": "Spare Parts",
                "modernization": "Modernization",
                "installations": "Installations",
                "blog": "Blog",
                "articles": "Articles",
                "tools": "Tools",
                "contact": "Contact",
                "aboutUs": "About Us",
                "profile": "Profile",
                "termsAndConditions": "Terms and Conditions",
                "privacyPolicy": "Privacy Policy",
                "shippingAndReturn": "Shipping and Return",
                "contact": "Contact",
                "contactUs": "Contact Us",
            },
            "AR": {
                "home": "الرئيسية",
                "courses": "الدورات",
                "articles": "المقالات",
                "tools": "الأدوات",
                "categories": "الفئات",
                "careers": "الوظائف",
                "audioArticles": "المقالات الصوتية",
                "aboutUs": "نبذة عنا",
                "classification": "التصنيفات",
                "passwordReset": "إستعادة كلمة المرور",
                "profile": "الصفحة الشخصية",
                "agenda": "الأجندة الإقتصادية"
            }
        }

        self.actions: dict = {
            "EN": {
                "login": "Login",
                "signup": "Sign Up",
                "seeMore": "See more",
                "getYoursNow": "Get Yours Now",
                "elevateYourExperience": "Elevate Your Experience",
                "rememberMe": "Remember me",
                "forgetPassword": "Forget Password?",
                "seeAllArticles": "See all articles",
                "seeMyArticles": "See My Articles",
                "seeAllJobs": "See All Jobs",
                "apply": "Apply",
                "applyNow": "Apply Now",
                "listen": "Listen",
                "share": "Share",
                "rate": "Rate",
                "comment": "Comment",
                "shareLinkVia": "Share article via...",
                "shareLink": "Share article's link!",
                "clear": "Clear",
                "findEmail": "Find Email",
                "sendCodeAgain": "Send code again",
                "changeEmail": "Change Email",
                "validateYourEmail": "Validate your email",
                "Validate": "Validate",
                "completeProfile": "Complete Profile",
                "submit": "Submit",
                "cancel": "Cancel",
                "checkThisOut": "Check this out!",
                "goBack": "Go Back",
                "continueCourse": "Continue Course",
                "enrollNow": "Enroll Now",
                "addToWishlist": "Add to wishlist",
                "seeRelativeArticles": "Relative Articles",
                "readArticle": "Read",
                "add": "Add",
                "comment": "Comment",
                "requestOption": "Request Option",
                "loading": "Loading...",
                "logout": "Logout",
                "pickPlan": "Pick Plan",
                "moreDetails": "More Details",
                "formClearedSuccessfully": "Form Cleared Successfully!",
                "ticketPlaced": "Your Ticket was Placed Successfully!",
                "bookNow": "Book Now",
                "bookMaintenance": "Book Maintenance",
                "sendInquery": "Send Inquery",
                "moreInfo": "More Info",
                "showPortfolio": "Show Portfolio",
                "requestSiteVisit": "Request Site Visit",
            },
            "AR": {
                "login": "تسجيل الدخول",
                "signup": "تسجيل الإشتراك",
                "seeMore": "شاهد المزيد",
                "rememberMe": "تذكرنى",
                "forgetPassword": "نسيت كلمة المرور?",
                "seeAllArticles": "تصفح جميع المقالات",
                "seeMyArticles": "تصفح مقالاتي",
                "seeAllJobs": "تصفح جميع الوظائف",
                "apply": "قدم",
                "applyNow": "قدم الآن",
                "listen": "استمع",
                "share": "شارك",
                "rate": "قيم",
                "comment": "أترك تعليقاً",
                "shareLinkVia": "شارك المقال عن طريق...",
                "shareLink": "شارك رابط المقال",
                "clear": "مسح",
                "findEmail": "البحث عن البريد الإلكتروني",
                "sendCodeAgain": "ارسل الرمز مجددا",
                "changeEmail": "تغيير الايميل",
                "validateYourEmail": "تحقق من صحة بريدك الإلكتروني",
                "Validate": "تحقق",
                "completeProfile": "أكمل الملف الشخصي",
                "submit": "تأكيد",
                "cancel": "إلغاء",
                "checkThisOut": "تحقق من هذا!",
                "goBack": "عُد",
                "continueCourse": "أكمل الدورة",
                "enrollNow": "التحق الآن",
                "addToWishlist": "أضف إلى قائمة الاهتمامات",


            }
        }
        
        self.forms: dict= {
            "EN": {
                "firstName": "First Name",
                "lastName": "Last Name",
                "email": "Email Adress",
                "phone": "Phone Number",
                "model": "Model",
                "plan": "Plan",
                "govern": "Govern",
                "area": "Area",
                "address": "Address",
                "geared": "Geared Elevators",
                "gearless": "Gearless Elevators",
                "homeLift": "Home Lift",
                "hydrolic": "Hydrolic Elevators",
                "category": "Category",
                "sparePart": "Spare Part"
                
            }
        }

        self.placeholders: dict = {
            "EN": {
                "search": "Search by name, keywords, etc...",
                "emailUsernameFieldPlaceholder": "Email Address",
                "emailFieldPlaceholder": "Email Address",
                "nameFieldPlaceholder": "Name",
                "passwordFieldPlaceholder": "Enter your Password!",
                "phoneFieldPlaceholder": "Enter your Phone Number!",
                "addressFieldPlaceholder": "Enter your Address!",
                "repasswordFieldPlaceholder": "Re-enter your Password!",
                "typeYourComment": "Type your comment...!",
                "messageFieldPlaceholder": "Type your message...!",
            }, "AR": {
                "search": "أبحث بالاسم، كلمة مفتاحية، أو آخرى",
                "emailUsernameFieldPlaceholder": "أدخل بريدك الإلكتروني",
                "emailFieldPlaceholder": "البريد الالكتروني",
                "nameFieldPlaceholder": "الاسم",
                "passwordFieldPlaceholder": "أدخل كلمة السر",
                "repasswordFieldPlaceholder": "أعد إدخال كلمة السر",
                "phoneFieldPlaceholder": "أدخل رقم الهاتف",
            }
        }

        self.salary_types: dict = {
            "EN": {
                0: "Per Month",
                1: "Per Task",
                2: "Per Milestone",
                3: "Per Project",
                4: "Long-time Contract",
                5: "Short-time Contract",
            },
            "AR": {
                0: "شهرياً",
                1: "مقابل المهمة",
                2: "مقابل المرحلة",
                3: "مقابل المشروع",
                4: "عقد طويل الأمد",
                5: "عقد قصير الأمد",
            },
        }

        self.job_types: dict = {
            "EN": {
                0: "Full Time",
                1: "Part Time",
                2: "Freelancer",
                3: "Hour Based Rate",
            },
            "AR": {
                0: "دوام كلي",
                1: "دوام جزئي",
                2: "مستقل",
                3: "حسب الوقت اللازم",
            },
        }
        
        self.errors: dict= {
            "EN": {
                "notFound": "Not Found",
                "notFoundMsg": "We didn't found the page or data you're searching for!",
                "internalServerError": "Internal Server Error",
                "internalServerErrorMsg": "There is an error. Try again later!",
                "notValidFirstName": "Please, Enter a valid First Name!",
                "notValidLastName": "Please, Enter a valid Last Name!",
                "notValidEmail": "Please, Enter a valid email!",
                "notValidAddress": "Please, Enter a valid address!",
                "notValidArea": "Please, Enter a valid area!",
                "notValidModel": "Please, Select the Elevators Model!",
                "notValidPlan": "Please, Select the Plan!",
                "notValidGovern": "Please, Select your Govern!",
                "notValidphoneNumber": "Please, Enter a valid phone number!",
                "notValidMessage": "Please, Make your message more detailed!",
                "notMessageOptionSelected": "Please, Select the request option!",
                "selectModelFirst": "Please, Select the Model First!",
                "formNotCompleted": "Please, Complete the form first!",
                "loading": "Loading...",
                "failed": "Failed!",
                "tryAgainLater": "Try again later!"
            },
            "AR": {
                "notFound": "غير موجود",
                "notFoundMsg": "لم نعثر على الصفحة أو البيانات التي تبحث عنها!",
                "internalServerError": "خطأ في الخادم الداخلي",
                "internalServerErrorMsg": "هنالك خطأ. حاول مرة أخرى في وقت لاحق!",
            }
        }

        self.agenda: dict= {
            "EN": {
                "event": "Event",
                "current": "Current",
                "pervious": "Pervious",
                "predicted": "Predicted",
                "importance": "Importance",
                "time": "Time",
            },
            "AR": {
                "currency": "العملة",
                "event": "الحدث",
                "current": "الحالي",
                "pervious": "السابق",
                "predicted": "المتوقع",
                "importance": "الأهمية",
                "time": "الوقت",
            }
        }

        self.courses= {
            "EN": {
                "completeSessions": "Completed Sessions",
                "courseCompletion": "Courses Completing",
                "testsPassed": "Tests Passed",
            },
            "AR": {
                "completeSessions": "المحاضرات المكتملة",
                "courseCompletion": "إكمال الدورة",
                "testsPassed": "الاختبارات التي تم تجاوزها",
            },
        }

        self.months= {
            "EN": {
                "January": "January",
                "February": "February",
                "March": "March",
                "April": "April",
                "May": "May",
                "June": "June",
                "July": "July",
                "August": "August",
                "September": "September",
                "October": "October",
                "November": "November",
                "December": "December",
            },
            "AR": {
                "January": "يناير ",
                "February": "فبراير ",
                "March": "مارس ",
                "April": "إبريل ",
                "May": "مايو ",
                "June": "يونيو ",
                "July": "يوليو ",
                "August": "أغسطس ",
                "September": "سبتمبر ",
                "October": "أكتوبر ",
                "November": "نوفمبر ",
                "December": "ديسمبر ",
            },            
        }
        self.status= {
            "EN": {
                "failed": "Failed!",
                "messageSentSuccessfully": "Message Sent Successfully!",
                "tryAgainLater": "Try again later!",
            }
        }
        
        self.cities = {
            "EN": {
                0: 'Alex',
                1: 'Aswan',
                2: 'Asyut',
                3: 'Behira',
                4: 'Beni Suef',
                5: 'Cairo',
                6: 'Dakahlia',
                7: 'Damietta',
                8: 'Faiyum',
                9: 'Gharbia',
                10: 'Giza',
                11: 'Ismailia',
                12: 'Kafr Sheikh',
                13: 'Luxor',
                14: 'Matruh',
                15: 'Minya',
                16: 'Monufia',
                17: 'Wadi Geded',
                18: 'North Sinai',
                19: 'Port Said',
                20: 'Qalyubia',
                21: 'Qena',
                22: 'Red Sea',
                23: 'Sharqia',
                24: 'Sohag',
                25: 'South Sinai',
                26: 'Suez',
            },
            "AR": {
                0: "الاسكندرية",
                1: "أسوان",
                2: "أسيوط",
                3: "البحيرة",
                4: "بني سويف",
                5: "القاهرة",
                6: "الدقهلية",
                7: "دمياط",
                8: "الفيوم",
                9: "الغربية",
                10: "الجيزة",
                11: "الاسماعيلية",
                12: "كفر الشيخ",
                13: "الأقصر",
                14: "مرسى مطروح",
                15: "المنيا",
                16: "المنوفية",
                17: "الوادي الجديد",
                18: "شمال سيناء",
                19: "بور سعيد ",
                20: "القليوبية",
                21: "قنا",
                22: "البحر الأحمر",
                23: "الشرقية",
                24: "سوهاج",
                25: "جنوب سيناء",
                26: "السويس"
            }
        }

        self.genders = {
            "en": {
                0: "Male",
                1: "Female",
                2: "Prefer not to say!",
            },
            "ar": {
                0: "ذكر",
                1: "أنثى",
                2: "تفضل ألا تقول"
            }
        }

    def update_content(self, content):
        return True






        
